env:
  global:
    - CC_TEST_REPORTER_ID=e0e1dd92dea75092ea6adbff7a2cd8ab2afab683a5f3ca4b5accfaa9b4a60bdf
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
cache:
  directories:
    - $HOME/.composer/cache/files
language: php
sudo: required
php:
  - '7.2'
  - '7.3'
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-software-properties
  - LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https apt-utils curl php-snmp
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - sudo php -m | grep snmp
install:
  - composer install
after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "${TRAVIS_PHP_VERSION:0:3}" == "7.2" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
